name: Build and Deploy to GitHub Releases

on:
  push:
    branches:
      - main

jobs:
  build-macos:
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.0"

      - name: Install dependencies
        run: flutter pub get

      - name: Build macOS app
        run: flutter build macos

      - name: Package macOS app as a zip
        run: |
          cd build/macos/Build/Products/Release
          zip -r "Socket_Probe_Macos.zip" "Socket Probe.app"

      - name: Upload macOS build to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          files: build/macos/Build/Products/Release/Socket_Probe_Macos.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.0"

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows app
        run: flutter build windows

      - name: Upload Windows build to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          files: build/windows/runner/Release/MyApp.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  generate-links:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Public Links
        run: |
          echo "Download macOS App: https://github.com/${{ github.repository }}/releases/latest/download/Socket_Probe.zip"
          echo "Download Windows App: https://github.com/${{ github.repository }}/releases/latest/download/MyApp.exe"
